In [1]:
# imports
import pandas as pd
import numpy as np
import os
from itertools import product

In [2]:
# list of features (total)
feat = [
    # home team features
    'HRk: previous season home team rank', 'HTeam: home team name', 
    'HAvAge: previous season home team average age', 'HGP: previous season home team games played', 
    'HW: previous season home team wins', 'HL: previous season home team losses', 
    'HOL: previous season home team overtime losses', 'HPTS: previous season home team points', 
    'HPTS%: previous season home team points percentage', 'HGF: previous season home team goals for', 
    'HGA: previous season home team goals against', 'HSOW: previous season home team shootout wins', 
    'HSOL: previous season home team shootout losses', 'HSRS: previous season home team simple rating system', 
    'HSOS: previous season home team strength of schedule', 'HGF/G: previous season home team goals for per game', 
    'HGA/G: previous season home team goals against per game', 'HPP: previous season home team power play goals', 
    'HPPO: previous season home team power play opportunities', 'HPP%: previous season home team power play percentage', 
    'HPPA: previous season home team power play goals against', 'HPPOA: previous season home team power play opportunities against', 
    'HPK%: previous season home team penalty kill percentage', 'HSH: previous season home team short-handed goals', 
    'HSHA: previous season home team short-handed goals against', 'HPIM/G: previous season home team penalty minutes per game', 
    'HoPIM/G: previous season home team opponent penalty minutes per game', 'HS: previous season home team shots', 
    'HS%: previous season home team shooting percentage', 'HSA: previous season home team shots against', 
    'HSV%: previous season home team save percentage', 'HSO: previous season home team shutouts',
    'HCAN: dummy variable for canadian home team', 'HSTAR: star player on home team',

    # visiting team features
    'VRk: previous season visitor team rank', 'VTeam: visitor team name', 
    'VAvAge: previous season visitor team average age', 'VGP: previous season visitor team games played', 
    'VW: previous season visitor team wins', 'VL: previous season visitor team losses', 
    'VOL: previous season visitor team overtime losses', 'VPTS: previous season visitor team points', 
    'VPTS%: previous season visitor team points percentage', 'VGF: previous season visitor team goals for', 
    'VGA: previous season visitor team goals against', 'VSOW: previous season visitor team shootout wins', 
    'VSOL: previous season visitor team shootout losses', 'VSRS: previous season visitor team simple rating system', 
    'VSOS: previous season visitor team strength of schedule', 'VGF/G: previous season visitor team goals for per game', 
    'VGA/G: previous season visitor team goals against per game', 'VPP: previous season visitor team power play goals', 
    'VPPO: previous season visitor team power play opportunities', 'VPP%: previous season visitor team power play percentage', 
    'VPPA: previous season visitor team power play goals against', 'VPPOA: previous season visitor team power play opportunities against', 
    'VPK%: previous season visitor team penalty kill percentage', 'VSH: previous season visitor team short-handed goals', 
    'VSHA: previous season visitor team short-handed goals against', 'VPIM/G: previous season visitor team penalty minutes per game', 
    'VoPIM/G: previous season visitor team opponent penalty minutes per game', 'VS: previous season visitor team shots', 
    'VS%: previous season visitor team shooting percentage', 'VSA: previous season visitor team shots against', 
    'VSV%: previous season visitor team save percentage', 'VSO: previous season visitor team shutouts',
    'VCAN: dummy variable for canadian visiting team', 'VSTAR: star player on home team',

    # general features
    'TDAY: dummy variable for Tuesday game',
    'WDAY: dummy variable for Wednesday game',
    'ThDAY: dummy variable for Thursday game',
    'FDAY: dummy variable for Friday game',
    'SDAY: dummy variable for Saturday game',
    'SuDAY: dummy variable for Sunday game',
    'DIV: dummy variable for in-division game',
    'CAP: home team capacity',
    'LCAP: natural logarithm of home team capacity'
]

In [3]:
# teams
can_teams = ['Montreal Canadiens', 'Toronto Maple Leafs', 'Vancouver Canucks',
             'Calgary Flames', 'Edmonton Oilers', 'Ottawa Senators',
             'Winnipeg Jets']

team_to_div = {
    'Toronto Maple Leafs': 'atl', 'Florida Panthers': 'atl', 'Tampa Bay Lightning': 'atl',
    'Detroit Red Wings': 'atl', 'Ottawa Senators': 'atl', 'Boston Bruins': 'atl',
    'Montreal Canadiens': 'atl', 'Buffalo Sabres': 'atl',
    
    'Carolina Hurricanes': 'met', 'New Jersey Devils': 'met', 'New York Rangers': 'met',
    'New York Islanders': 'met', 'Pittsburgh Penguins': 'met', 'Washington Capitals': 'met',
    'Philadelphia Flyers': 'met', 'Columbus Blue Jackets': 'met',
    
    'Colorado Avalanche': 'cen', 'Dallas Stars': 'cen', 'Winnipeg Jets': 'cen',
    'Minnesota Wild': 'cen', 'Nashville Predators': 'cen', 'St. Louis Blues': 'cen',
    'Arizona Coyotes': 'cen', 'Chicago Blackhawks': 'cen',
    
    'Vegas Golden Knights': 'pac', 'Edmonton Oilers': 'pac', 'Los Angeles Kings': 'pac',
    'Seattle Kraken': 'pac', 'Calgary Flames': 'pac', 'Vancouver Canucks': 'pac',
    'San Jose Sharks': 'pac', 'Anaheim Ducks': 'pac'
}

In [4]:
# BASE DATAFRAMES (PUT ALL SEASONS TOGETHER IN ONE DF
# first build df per season, then combine all seasons

# clean stats data
def clean_stat(df_stat_prev):
    '''
    clean statistics data so that it can be combined with the attendance data
    '''
    
    # --> convert to numeric
    df_stat_prev[['Rk', 'AvAge', 'GP', 'W', 'L', 'OL', 'PTS', 'PTS%', 'GF', 'GA',
           'SOW', 'SOL', 'SRS', 'SOS', 'GF/G', 'GA/G', 'PP', 'PPO', 'PP%', 'PPA',
           'PPOA', 'PK%', 'SH', 'SHA', 'PIM/G', 'oPIM/G', 'S', 'S%', 'SA', 'SV%',
           'SO']] = df_stat_prev[['Rk', 'AvAge', 'GP', 'W', 'L', 'OL', 'PTS', 'PTS%', 'GF', 'GA',
           'SOW', 'SOL', 'SRS', 'SOS', 'GF/G', 'GA/G', 'PP', 'PPO', 'PP%', 'PPA',
           'PPOA', 'PK%', 'SH', 'SHA', 'PIM/G', 'oPIM/G', 'S', 'S%', 'SA', 'SV%',
           'SO']].apply(pd.to_numeric, errors = 'coerce')

    return df_stat_prev

# clean attendance data
def clean_att(df_res):
    '''
    clean attendance data
    remove games with extreme outliers in attendance
    ensure attendance is numeric
    '''
    
    # make sure attendance is numeric
    df_res['Attendance'] = pd.to_numeric(df_res['Attendance'], errors = 'coerce')
    
    # games with notes (specialty games) --> remove these entries cause they'll just mess up the data
    df_notes = df_res[df_res['Notes'].notna() & (df_res['Notes'] != '')]
    df_res = df_res.drop(df_notes.index)

    '''
    # games with wack attendance
    # 2022 season still partly affected by COVID-19 --> remove these entries cause they'll just mess up the data
    df_weird_att = df_res[(df_res['Attendance'] >= 30000) | (df_res['Attendance'] <= 12000) | (df_res['Attendance'].isna())]
    df_res = df_res.drop(df_weird_att.index)
    '''

    '''
    df_weird_att = df_res[(df_res['Attendance'] >= df_res['Capacity'] + 2500) | (df_res['Attendance'] <= df_res['Capacity'] - 2500) | (df_res['Attendance'].isna())]
    df_res = df_res.drop(df_weird_att.index)
    '''
    
    # re-index
    df_res = df_res.reset_index(drop = True)

    return df_res

In [5]:
# combine stats and attendance data
def season_data(df_res, df_stat_prev, df_arena, df_star_prev):
    '''
    combine attendance data with the cleaned statistics data from the previous season
    for full list of features, see [feat]
    df_res: current season results
        trying to predict attendance for current season
    df_stat_prev: previous season statistics
        use previous season statistics for prediction (with additional game day variables)
    df_arena: current season arena capacities
        add arena capacity (for current season) as variable
    df_star_prev: previous season's best players
    returns combined df
    '''

    ###
    # make new df with desired variables
    df_vars = pd.DataFrame()
    
    # attendance
    df_vars['A'] = df_res['Attendance']
    
    # log attendance
    df_vars['LA'] = np.log(df_vars['A'])
    
    # home team
    df_vars['H'] = df_res['Home']
    
    # visiting team
    df_vars['V'] = df_res['Visitor']

    ### renaming of Phoenix Coyotes --> Arizona Coyotes
    if ('Arizona Coyotes' in df_vars['V'].values) and ('Arizona Coyotes' not in df_stat_prev['Team'].values):
        df_stat_prev['Team'] = df_stat_prev['Team'].replace('Phoenix Coyotes', 'Arizona Coyotes')

    ### home team variables
    df_vars = df_vars.join(
        df_stat_prev.set_index('Team').add_prefix('H'), 
        on = 'H'
    )

    # home team canadian team dummy (1 - canadian, 0 - otherwise)
    df_vars['HCAN'] = df_vars['H'].apply(lambda x: 1 if x in can_teams else 0)

    ### visiting team variables
    df_vars = df_vars.join(
        df_stat_prev.set_index('Team').add_prefix('V'), 
        on = 'V'
    )

    # visiting team canadian team dummy (1 - canadian, 0 - otherwise)
    df_vars['VCAN'] = df_vars['V'].apply(lambda x: 1 if x in can_teams else 0)
    
    
    ### game variables
    # no monday dummy --> multicollinearity    
    # tuesday dummy (1 - tuesday, 0 - otherwise)
    df_vars['TDAY'] = df_res['Day'].isin(['Tuesday']).astype(int)
    
    # wednesday dummy (1 - wednesday, 0 - otherwise)
    df_vars['WDAY'] = df_res['Day'].isin(['Wednesday']).astype(int)
    
    # thursday dummy (1 - thursday, 0 - otherwise)
    df_vars['ThDAY'] = df_res['Day'].isin(['Thursday']).astype(int)
    
    # friday dummy (1 - friday, 0 - otherwise)
    df_vars['FDAY'] = df_res['Day'].isin(['Friday']).astype(int)
    
    # saturday dummy (1 - saturday, 0 - otherwise)
    df_vars['SDAY'] = df_res['Day'].isin(['Saturday']).astype(int)
    
    # sunday dummy (1 - sunday, 0 - otherwise)
    df_vars['SuDAY'] = df_res['Day'].isin(['Sunday']).astype(int)
    
    # in-division game
    df_vars['DIV'] = df_vars.apply(
        lambda row: 1 if team_to_div.get(row['H']) == team_to_div.get(row['V']) else 0, axis = 1
    )

    # capacity of home team
    df_vars['CAP'] = df_vars['H'].map(df_arena.set_index('Team')['Capacity'])

    # log capacity
    df_vars['LCAP'] = np.log(df_vars['CAP'])

    # percentage attendance
    df_vars['PA'] = df_vars['A'] / df_vars['CAP']

    ### star players
    # Create a set of star teams from df_star_prev
    star_teams_set = set(df_star_prev['Team'])
    
    # Home team star player dummy (1 if home team is in the star teams, 0 otherwise)
    df_vars['HSTAR'] = df_vars['H'].apply(
        lambda team: 1 if team in star_teams_set else 0
    )
    
    # Visiting team star player dummy (1 if visiting team is in the star teams, 0 otherwise)
    df_vars['VSTAR'] = df_vars['V'].apply(
        lambda team: 1 if team in star_teams_set else 0
    )

    return df_vars

In [6]:
# load each season results (attendance), prev season stats, and season arenas
def load_and_store_df(year: int):
    '''
    loads season results, prev season stats, and season arenas
    calls function: season_data to combine into df
    returns combined df
    '''

    season_str = f'{year - 1}-{str(year)[2:]}'
    season_prev_str = f'{year - 2}-{str(year - 1)[2:]}'
    
    file_res = f'season results/{season_str} season results.csv'
    file_stat = f'season stats csv/{season_prev_str} season stats.csv'
    file_arena = f'season arenas/{season_str} season arenas.csv'
    file_stars = f'top skaters data/{season_prev_str} top 15 skaters.csv'

    df_res = pd.read_csv(file_res)
    df_prev_stat = pd.read_csv(file_stat)
    df_arena = pd.read_csv(file_arena)
    df_prev_stars = pd.read_csv(file_stars)

    # preprocess
    df_res_clean = clean_att(df_res)
    df_stat_clean = clean_stat(df_prev_stat)

    df_vars = season_data(df_res_clean, df_stat_clean, df_arena, df_prev_stars)

    # wack attendance
    df_weird_att = df_vars[(df_vars['A'] >= df_vars['CAP'] * 1.50) | (df_vars['A'] <= df_vars['CAP'] * 0.50) | (df_vars['A'].isna())]
    df_vars = df_vars.drop(df_weird_att.index)
    
    # re-index
    df_vars = df_vars.reset_index(drop = True)

    return df_vars

In [7]:
# combine df for each season into one giant df
years = [2014, 2015, 2016, 2017, 2018, 2019, 2022, 2023, 2024]

df_vars_total = pd.DataFrame()
for year in years:
    df_vars = load_and_store_df(year)
    df_vars_total = pd.concat([df_vars_total, df_vars], ignore_index = True)

In [8]:
# only rows that contain NaN values are the rows where its the first season the Kraken or Golden Knights joined the league
df_vars_total[df_vars_total.isnull().any(axis = 1)]

,A,LA,H,V,HRk,HAvAge,HGP,HW,HL,HOL,...,ThDAY,FDAY,SDAY,SuDAY,DIV,CAP,LCAP,PA,HSTAR,VSTAR
4885,18532.0,9.827254,Dallas Stars,Vegas Golden Knights,24.0,28.5,82.0,34.0,37.0,11.0,...,0,1,0,0,0,18532.0,9.827254,1.000000,0,0
4888,17125.0,9.748295,Arizona Coyotes,Vegas Golden Knights,28.0,27.3,82.0,30.0,42.0,10.0,...,0,0,1,0,0,17125.0,9.748295,1.000000,0,0
4915,18191.0,9.808682,Vegas Golden Knights,Arizona Coyotes,NaN,NaN,NaN,NaN,NaN,NaN,...,0,0,0,0,0,17367.0,9.762327,1.047446,0,0
4932,17645.0,9.778208,Vegas Golden Knights,Detroit Red Wings,NaN,NaN,NaN,NaN,NaN,NaN,...,0,1,0,0,0,17367.0,9.762327,1.016007,0,0
4949,17562.0,9.773493,Vegas Golden Knights,Boston Bruins,NaN,NaN,NaN,NaN,NaN,NaN,...,0,0,0,1,0,17367.0,9.762327,1.011228,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10956,4600.0,8.433812,Arizona Coyotes,Nashville Predators,27.0,26.4,82.0,28.0,40.0,14.0,...,1,0,0,0,1,NaN,NaN,NaN,0,0
10971,4600.0,8.433812,Arizona Coyotes,New York Rangers,27.0,26.4,82.0,28.0,40.0,14.0,...,0,0,1,0,0,NaN,NaN,NaN,0,0
11002,4600.0,8.433812,Arizona Coyotes,Vancouver Canucks,27.0,26.4,82.0,28.0,40.0,14.0,...,0,0,0,0,0,NaN,NaN,NaN,0,1
11017,4600.0,8.433812,Arizona Coyotes,Vegas Golden Knights,27.0,26.4,82.0,28.0,40.0,14.0,...,0,1,0,0,0,NaN,NaN,NaN,0,0
11108,4600.0,8.433812,Arizona Coyotes,Edmonton Oilers,27.0,26.4,82.0,28.0,40.0,14.0,...,0,0,0,0,0,NaN,NaN,NaN,0,1

In [9]:
# for now: drop these values, since regressions will probably drop them anyways
# and I don't really know how else to deal with them lol
df_vars_total = df_vars_total.dropna()
df_vars_total

,A,LA,H,V,HRk,HAvAge,HGP,HW,HL,HOL,...,ThDAY,FDAY,SDAY,SuDAY,DIV,CAP,LCAP,PA,HSTAR,VSTAR
0,22158.0,10.005954,Chicago Blackhawks,Washington Capitals,1.0,26.8,48.0,36.0,7.0,5.0,...,0,0,0,0,0,19717.0,9.889236,1.123802,1,1
1,16839.0,9.731453,Edmonton Oilers,Winnipeg Jets,24.0,26.4,48.0,19.0,22.0,7.0,...,0,0,0,0,0,17100.0,9.746834,0.984737,1,0
2,21273.0,9.965194,Montreal Canadiens,Toronto Maple Leafs,4.0,27.8,48.0,29.0,14.0,5.0,...,0,0,0,0,1,21105.0,9.957265,1.007960,0,1
3,18007.0,9.798516,Colorado Avalanche,Anaheim Ducks,29.0,26.7,48.0,16.0,25.0,7.0,...,0,0,0,0,0,17809.0,9.787459,1.011118,0,1
4,20066.0,9.906782,Detroit Red Wings,Buffalo Sabres,12.0,28.2,48.0,24.0,16.0,8.0,...,0,0,0,0,1,20027.0,9.904837,1.001947,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11113,18129.0,9.805268,Colorado Avalanche,Edmonton Oilers,6.0,28.1,82.0,51.0,24.0,7.0,...,1,0,0,0,0,17809.0,9.787459,1.017968,1,1
11114,18145.0,9.806150,Los Angeles Kings,Chicago Blackhawks,10.0,28.7,82.0,47.0,25.0,10.0,...,1,0,0,0,0,18230.0,9.810824,0.995337,0,0
11115,19138.0,9.859431,Minnesota Wild,Seattle Kraken,11.0,29.3,82.0,46.0,25.0,11.0,...,1,0,0,0,0,17954.0,9.795568,1.065946,0,0
11116,18109.0,9.804164,Vegas Golden Knights,Anaheim Ducks,4.0,29.1,82.0,51.0,22.0,9.0,...,1,0,0,0,1,17367.0,9.762327,1.042725,0,0
11117,15225.0,9.630694,Winnipeg Jets,Vancouver Canucks,14.0,28.7,82.0,46.0,33.0,3.0,...,1,0,0,0,0,15321.0,9.636980,0.993734,0,1

In [10]:
# store into giant csv file
file_name = 'attendance data with features.csv'
file_path = os.path.join(file_name)
df_vars_total.to_csv(file_path, index = False)

In [11]:
# summary statistics for numerical columns
df_vars_total.describe()

,A,LA,HRk,HAvAge,HGP,HW,HL,HOL,HPTS,HPTS%,...,ThDAY,FDAY,SDAY,SuDAY,DIV,CAP,LCAP,PA,HSTAR,VSTAR
count,10874.000000,10874.000000,10874.000000,10874.000000,10874.000000,10874.000000,10874.000000,10874.000000,10874.000000,10874.000000,...,10874.000000,10874.000000,10874.000000,10874.000000,10874.000000,10874.000000,10874.000000,10874.000000,10874.000000,10874.000000
mean,17389.040923,9.753438,15.581939,28.010962,75.480228,37.992091,28.738183,8.749954,84.734136,0.561189,...,0.196432,0.103458,0.237171,0.101986,0.335019,18252.241603,9.809768,0.952288,0.346699,0.340261
std,2325.037637,0.147616,8.810332,1.044512,12.549419,10.175736,8.760723,3.199994,20.737906,0.099712,...,0.397317,0.304570,0.425368,0.302644,0.472019,1212.486959,0.068051,0.106813,0.475941,0.473819
min,8679.000000,9.068662,1.000000,25.800000,48.000000,15.000000,7.000000,0.000000,36.000000,0.293000,...,0.000000,0.000000,0.000000,0.000000,0.000000,13900.000000,9.539644,0.500053,0.000000,0.000000
25%,16514.000000,9.711964,8.000000,27.300000,82.000000,30.000000,23.000000,7.000000,70.000000,0.491000,...,0.000000,0.000000,0.000000,0.000000,0.000000,17435.000000,9.766235,0.931443,0.000000,0.000000
50%,18006.000000,9.798460,15.000000,28.100000,82.000000,39.000000,28.000000,8.000000,88.000000,0.573000,...,0.000000,0.000000,0.000000,0.000000,0.000000,18347.000000,9.817221,1.000000,0.000000,0.000000
75%,18813.750000,9.842343,23.000000,28.700000,82.000000,46.000000,35.000000,11.000000,101.000000,0.634000,...,0.000000,0.000000,0.000000,0.000000,1.000000,19092.000000,9.857025,1.002989,1.000000,1.000000
max,22247.000000,10.009962,32.000000,31.000000,82.000000,65.000000,56.000000,18.000000,135.000000,0.823000,...,1.000000,1.000000,1.000000,1.000000,1.000000,21105.000000,9.957265,1.163309,1.000000,1.000000

In [16]:
# combine stats and attendance data (and add canadian team dummy)
def stats_arena_data(df_stat_prev, df_arena):
    '''
    combine attendance data with the cleaned statistics data from the previous season
    for full list of features, see [feat]
    df_res: current season results
        trying to predict attendance for current season
    df_stat_prev: previous season statistics
        use previous season statistics for prediction (with additional game day variables)
    df_arena: current season arena capacities
        add arena capacity (for current season) as variable
    returns combined df
    '''

    ###
    # make new df with desired variables
    df_vars = df_stat_prev.copy()

    # canadian team dummy (1 - canadian, 0 - otherwise)
    df_vars['CAN'] = df_vars['Team'].apply(lambda x: 1 if x in can_teams else 0)

    # capacity
    df_vars['CAP'] = df_vars['Team'].map(df_arena.set_index('Team')['Capacity'])

    # log capacity
    df_vars['LCAP'] = np.log(df_vars['CAP'])

    # Reset index to move "Rk" to a column, then set "Team" as the new index
    df_vars = df_vars.reset_index().set_index('Team')
    
    return df_vars

def load_and_store_df_predictors(year: int):
    '''
    loads season results, prev season stats, and season arenas
    calls function: season_data to combine into df
    returns combined df
    '''

    season_str = f'{year - 1}-{str(year)[2:]}'
    season_prev_str = f'{year - 2}-{str(year - 1)[2:]}'
    
    file_stat = f'season stats csv/{season_prev_str} season stats.csv'
    file_arena = f'season arenas/{season_str} season arenas.csv'
    file_stars = f'top skaters data/{season_prev_str} top 15 skaters.csv'

    # stats
    df_prev_stat = pd.read_csv(file_stat)
    
    # remove 'league average' row
    df_prev_stat = df_prev_stat[df_prev_stat['Team'] != 'League Average']

    # remove Arizona Coyotes
    df_prev_stat = df_prev_stat[df_prev_stat['Team'] != 'Arizona Coyotes']

    # arena
    df_arena = pd.read_csv(file_arena)

    # preprocess
    df_stat_clean = clean_stat(df_prev_stat)

    # add arena capacities
    df_vars = stats_arena_data(df_stat_clean, df_arena)

    # re-index
    df_vars = df_vars.reset_index()
    df_vars = df_vars.drop(columns='index')

    # stars
    df_arena = pd.read_csv(file_arena)

    # Create a set of star teams
    star_teams_set = set(df_prev_stars['Team'])

    # Home team star player dummy (1 if home team is in the star teams, 0 otherwise)
    df_vars['Star_Player_H'] = df_vars['Team'].apply(
        lambda team: 1 if team in star_teams_set else 0
    )
    
    # Visiting team star player dummy (1 if visiting team is in the star teams, 0 otherwise)
    df_vars['Star_Player_V'] = df_vars['Team'].apply(
        lambda team: 1 if team in star_teams_set else 0
    )
    
    # Re-index and clean up
    df_vars = df_vars.reset_index(drop=True)

    return df_vars

In [17]:
# 2023-24 season statistics and arenas (no attendance, used for predicting 2024-25)
# want: statistics combined with capacity and canadian team dummy
df_2425_predictors = load_and_store_df_predictors(2025)

# store into csv file
file_name = 'data season 2024-25.csv'
file_path = os.path.join(file_name)
df_2425_predictors.to_csv(file_path, index = False)

NameError: name 'df_prev_stars' is not defined

In [14]:
def generate_matchup_data(df_vars):
    '''
    Create a DataFrame containing all possible matchups with home (H) and visiting (V) team statistics.
    df_vars: DataFrame with team statistics.
    Returns: DataFrame with all matchups.
    '''

    # Generate all possible matchups (excluding same team matchups)
    teams = df_vars['Team'].unique()
    matchups = [(h, v) for h, v in product(teams, repeat=2) if h != v]

    # Convert to DataFrame
    df_matchups = pd.DataFrame(matchups, columns=['H', 'V'])

    # Merge Home team statistics
    df_home = df_vars.add_prefix('H')
    df_matchups = df_matchups.merge(df_home, left_on='H', right_on='HTeam', how='left')
    df_matchups = df_matchups.drop(columns=['HTeam'])  # Drop redundant column

    # Merge Visiting team statistics
    df_away = df_vars.add_prefix('V')
    df_matchups = df_matchups.merge(df_away, left_on='V', right_on='VTeam', how='left')
    df_matchups = df_matchups.drop(columns=['VTeam'])  # Drop redundant column

    # drop visiting team capacity
    df_matchups = df_matchups.drop(columns = ['VCAP', 'VLCAP'])

    # rename home team capacity
    df_matchups = df_matchups.rename(columns={'HCAP': 'CAP', 'HLCAP': 'LCAP'})

    # Add day-of-week columns initialized to 0
    for day in ['TDAY', 'WDAY', 'ThDAY', 'FDAY', 'SDAY', 'SuDAY']:
        df_matchups[day] = 0

    # in-division game
    df_matchups['DIV'] = df_matchups.apply(
        lambda row: 1 if team_to_div.get(row['H']) == team_to_div.get(row['V']) else 0, axis = 1
    )

    return df_matchups

In [15]:
# generate matchups
df_matchups = generate_matchup_data(df_2425_predictors)

# store into csv file
file_name = '2024-25 matchups features.csv'
file_path = os.path.join(file_name)
df_matchups.to_csv(file_path, index = False)